// Storage + loading for "form definitions" — the artifact the generator emits
// and the runtime bot executes. Each definition lives in forms/<id>.json:
//
//   {
//     meta:        { id, title, version, generatedAt },
//     systemPrompt: "<LLM conversation instructions>",
//     extractionSchema: { ... }                // JSON shape for /export
//     cards:       [ { id, title, intro, fields:[...] } ]
//   }
//
// forms/active.json holds { id } — which definition the bot currently runs.

const fs = require('fs');
const path = require('path');

const FORMS_DIR = path.join(__dirname, '..', 'forms');
const ACTIVE_PATH = path.join(FORMS_DIR, 'active.json');

function ensureDir() {
  if (!fs.existsSync(FORMS_DIR)) fs.mkdirSync(FORMS_DIR, { recursive: true });
}

function slugify(s) {
  return String(s || 'form')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'form';
}

function listForms() {
  ensureDir();
  return fs
    .readdirSync(FORMS_DIR)
    .filter((f) => f.endsWith('.json') && f !== 'active.json')
    .map((f) => {
      try {
        const def = JSON.parse(fs.readFileSync(path.join(FORMS_DIR, f), 'utf8'));
        return { id: def.meta?.id || f.replace(/\.json$/, ''), title: def.meta?.title || f, version: def.meta?.version || '' };
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

function loadForm(id) {
  ensureDir();
  const p = path.join(FORMS_DIR, `${id}.json`);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

// Persist a definition; assigns/sanitizes an id and returns the stored object.
function saveForm(def) {
  ensureDir();
  def.meta = def.meta || {};
  let id = def.meta.id || slugify(def.meta.title || 'form');
  // avoid clobbering a different existing form with the same slug
  let base = id, n = 1;
  while (fs.existsSync(path.join(FORMS_DIR, `${id}.json`))) {
    const existing = loadForm(id);
    if (existing && existing.meta?.id === def.meta.id) break; // same form, overwrite
    if (def.meta.id) break; // explicit id → overwrite
    id = `${base}-${++n}`;
  }
  def.meta.id = id;
  def.meta.version = def.meta.version || '1.0';
  fs.writeFileSync(path.join(FORMS_DIR, `${id}.json`), JSON.stringify(def, null, 2));
  return def;
}

function getActiveId() {
  ensureDir();
  if (fs.existsSync(ACTIVE_PATH)) {
    try {
      return JSON.parse(fs.readFileSync(ACTIVE_PATH, 'utf8')).id || null;
    } catch {
      /* fall through */
    }
  }
  const forms = listForms();
  return forms.length ? forms[0].id : null;
}

function setActiveId(id) {
  ensureDir();
  fs.writeFileSync(ACTIVE_PATH, JSON.stringify({ id }, null, 2));
}

function getActiveForm() {
  const id = getActiveId();
  return id ? loadForm(id) : null;
}

// Render a definition's prompt + schema as a prompts.js module string,
// matching the format of src/prompts.js (verbatim backtick template).
function renderPromptsJs(def) {
  const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const schema =
    typeof def.extractionSchema === 'string'
      ? def.extractionSchema
      : JSON.stringify(def.extractionSchema, null, 2);
  return (
    `// Generated by the Questionnaire Prompt Generator on ${def.meta?.generatedAt || ''}.\n` +
    `// Source form: ${def.meta?.title || def.meta?.id || 'untitled'} (v${def.meta?.version || '1.0'}).\n\n` +
    `const SYSTEM_PROMPT = \`${esc(def.systemPrompt)}\`;\n\n` +
    `const EXTRACTION_SCHEMA = \`${esc(schema)}\`;\n\n` +
    `module.exports = { SYSTEM_PROMPT, EXTRACTION_SCHEMA };\n`
  );
}

module.exports = {
  FORMS_DIR,
  slugify,
  listForms,
  loadForm,
  saveForm,
  getActiveId,
  setActiveId,
  getActiveForm,
  renderPromptsJs,
};
